// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformType string

const (
	PlatformTypeWeb    PlatformType = "web"
	PlatformTypeMobile PlatformType = "mobile"
	PlatformTypeIos    PlatformType = "ios"
)

func (e *PlatformType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlatformType(s)
	case string:
		*e = PlatformType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlatformType: %T", src)
	}
	return nil
}

type NullPlatformType struct {
	PlatformType PlatformType
	Valid        bool // Valid is true if PlatformType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlatformType) Scan(value interface{}) error {
	if value == nil {
		ns.PlatformType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlatformType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlatformType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlatformType), nil
}

type RoleType string

const (
	RoleTypeSuperAdmin  RoleType = "super_admin"
	RoleTypeAdmin       RoleType = "admin"
	RoleTypeExamCreator RoleType = "exam_creator"
	RoleTypeReviewer    RoleType = "reviewer"
	RoleTypeProctor     RoleType = "proctor"
	RoleTypeSupport     RoleType = "support"
	RoleTypeCandidate   RoleType = "candidate"
	RoleTypeViewer      RoleType = "viewer"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType
	Valid    bool // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type UserPlanType string

const (
	UserPlanTypeFree         UserPlanType = "free"
	UserPlanTypePremium      UserPlanType = "premium"
	UserPlanTypeSubscription UserPlanType = "subscription"
)

func (e *UserPlanType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserPlanType(s)
	case string:
		*e = UserPlanType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserPlanType: %T", src)
	}
	return nil
}

type NullUserPlanType struct {
	UserPlanType UserPlanType
	Valid        bool // Valid is true if UserPlanType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserPlanType) Scan(value interface{}) error {
	if value == nil {
		ns.UserPlanType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserPlanType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserPlanType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserPlanType), nil
}

type Permission struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
}

type RolePermission struct {
	Role         RoleType
	PermissionID pgtype.UUID
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	FirstName    pgtype.Text
	LastName     pgtype.Text
	FullName     pgtype.Text
	Role         RoleType
	Plan         UserPlanType
	IsActive     bool
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type UserSession struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Platform       PlatformType
	RefreshToken   string
	AccessTokenJti pgtype.UUID
	ExpiresAt      pgtype.Timestamptz
	IsRevoked      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}
