// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO role_permissions (role, permission_id)
VALUES ($1,$2)
ON CONFLICT DO NOTHING
`

type AssignPermissionToRoleParams struct {
	Role         RoleType
	PermissionID pgtype.UUID
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.Role, arg.PermissionID)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (
  user_id,
  platform,
  refresh_token,
  access_token_jti,
  expires_at
)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, user_id, platform, refresh_token, access_token_jti, expires_at, is_revoked, created_at, updated_at, deleted_at
`

type CreateSessionParams struct {
	UserID         pgtype.UUID
	Platform       PlatformType
	RefreshToken   string
	AccessTokenJti pgtype.UUID
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Platform,
		arg.RefreshToken,
		arg.AccessTokenJti,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.RefreshToken,
		&i.AccessTokenJti,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  password_hash,
  first_name,
  last_name,
  full_name,
  role,
  plan
)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, email, password_hash, first_name, last_name, full_name, role, plan, is_active, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	FirstName    pgtype.Text
	LastName     pgtype.Text
	FullName     pgtype.Text
	Role         RoleType
	Plan         UserPlanType
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.FullName,
		arg.Role,
		arg.Plan,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Role,
		&i.Plan,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM user_sessions
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM user_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (
  SELECT 1 FROM users
  WHERE email = $1
  AND deleted_at IS NULL
)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getPermissionByName = `-- name: GetPermissionByName :one
SELECT id, name, description
FROM permissions
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByName, name)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getPermissionsByRole = `-- name: GetPermissionsByRole :many
SELECT p.id, p.name, p.description
FROM permissions p
JOIN role_permissions rp
ON rp.permission_id = p.id
WHERE rp.role = $1
`

func (q *Queries) GetPermissionsByRole(ctx context.Context, role RoleType) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, platform, refresh_token, access_token_jti, expires_at, is_revoked, created_at, updated_at, deleted_at
FROM user_sessions
WHERE refresh_token = $1
AND is_revoked = FALSE
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshToken)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.RefreshToken,
		&i.AccessTokenJti,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, full_name, role, plan, is_active, last_login_at, created_at, updated_at, deleted_at
FROM users
WHERE email = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Role,
		&i.Plan,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, full_name, role, plan, is_active, last_login_at, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Role,
		&i.Plan,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT p.name
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN users u ON u.role = rp.role
WHERE u.id = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, id pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, description
FROM permissions
ORDER BY name
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, platform, refresh_token, access_token_jti, expires_at, is_revoked, created_at, updated_at, deleted_at
FROM user_sessions
WHERE user_id = $1
AND is_revoked = FALSE
AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID pgtype.UUID) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.RefreshToken,
			&i.AccessTokenJti,
			&i.ExpiresAt,
			&i.IsRevoked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role = $1
AND permission_id = $2
`

type RemovePermissionFromRoleParams struct {
	Role         RoleType
	PermissionID pgtype.UUID
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, removePermissionFromRole, arg.Role, arg.PermissionID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions
SET is_revoked = TRUE
WHERE user_id = $1
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_sessions
SET is_revoked = TRUE
WHERE refresh_token = $1
`

func (q *Queries) RevokeSession(ctx context.Context, refreshToken string) error {
	_, err := q.db.Exec(ctx, revokeSession, refreshToken)
	return err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE user_sessions
SET is_revoked = TRUE
WHERE id = $1
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionByID, id)
	return err
}

const roleHasPermission = `-- name: RoleHasPermission :one
SELECT EXISTS (
  SELECT 1
  FROM role_permissions rp
  JOIN permissions p
  ON rp.permission_id = p.id
  WHERE rp.role = $1
  AND p.name = $2
)
`

type RoleHasPermissionParams struct {
	Role RoleType
	Name string
}

func (q *Queries) RoleHasPermission(ctx context.Context, arg RoleHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, roleHasPermission, arg.Role, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setUserActiveStatus = `-- name: SetUserActiveStatus :exec
UPDATE users
SET is_active = $2
WHERE id = $1
`

type SetUserActiveStatusParams struct {
	ID       pgtype.UUID
	IsActive bool
}

func (q *Queries) SetUserActiveStatus(ctx context.Context, arg SetUserActiveStatusParams) error {
	_, err := q.db.Exec(ctx, setUserActiveStatus, arg.ID, arg.IsActive)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
  first_name = $2,
  last_name = $3,
  full_name = $4
WHERE id = $1
RETURNING id, email, password_hash, first_name, last_name, full_name, role, plan, is_active, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID        pgtype.UUID
	FirstName pgtype.Text
	LastName  pgtype.Text
	FullName  pgtype.Text
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Role,
		&i.Plan,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
