// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkInsertAttemptMap implements pgx.CopyFromSource.
type iteratorForBulkInsertAttemptMap struct {
	rows                 []BulkInsertAttemptMapParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertAttemptMap) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertAttemptMap) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AttemptID,
		r.rows[0].QuestionID,
		r.rows[0].SectionID,
		r.rows[0].OrderIndex,
		r.rows[0].ShuffledOptions,
	}, nil
}

func (r iteratorForBulkInsertAttemptMap) Err() error {
	return nil
}

// ============================================================
// ATTEMPT QUESTION MAP
// ============================================================
func (q *Queries) BulkInsertAttemptMap(ctx context.Context, arg []BulkInsertAttemptMapParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"attempt_question_map"}, []string{"attempt_id", "question_id", "section_id", "order_index", "shuffled_options"}, &iteratorForBulkInsertAttemptMap{rows: arg})
}
