// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID               pgtype.UUID
	AttemptID        pgtype.UUID
	QuestionID       string
	SelectedAnswer   []byte
	IsCorrect        pgtype.Bool
	MarksAwarded     pgtype.Float8
	QuestionSnapshot []byte
}

type Attempt struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	ExamID           pgtype.UUID
	Status           interface{}
	TotalScore       pgtype.Float8
	TimeTakenSeconds pgtype.Int4
	StartedAt        pgtype.Timestamp
	CompletedAt      pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type AttemptQuestionMap struct {
	AttemptID       pgtype.UUID
	QuestionID      string
	SectionID       pgtype.UUID
	OrderIndex      pgtype.Int4
	ShuffledOptions []byte
}

type AttemptSectionScore struct {
	AttemptID pgtype.UUID
	SectionID pgtype.UUID
	Score     pgtype.Float8
	Correct   pgtype.Int4
	Wrong     pgtype.Int4
}

type Exam struct {
	ID              pgtype.UUID
	Name            string
	ExamType        interface{}
	DurationMinutes int32
	TotalMarks      int32
	IsActive        pgtype.Bool
	CreatedAt       pgtype.Timestamp
}

type ExamQuestionSet struct {
	ID                     pgtype.UUID
	ExamID                 pgtype.UUID
	SectionID              pgtype.UUID
	QuestionSetID          string
	QuestionCount          int32
	DifficultyDistribution []byte
}

type ExamSection struct {
	ID              pgtype.UUID
	ExamID          pgtype.UUID
	Name            string
	SubjectID       pgtype.UUID
	TimeLimit       pgtype.Int4
	QuestionCount   pgtype.Int4
	OrderIndex      pgtype.Int4
	IsSwitchAllowed pgtype.Bool
	IsActive        pgtype.Bool
}

type ExamSetting struct {
	ExamID             pgtype.UUID
	IsPublished        pgtype.Bool
	ShuffleQuestions   pgtype.Bool
	ShuffleOptions     pgtype.Bool
	AllowSectionSwitch pgtype.Bool
}

type Subject struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
}
