// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertAttemptMapParams struct {
	AttemptID       pgtype.UUID
	QuestionID      string
	SectionID       pgtype.UUID
	OrderIndex      pgtype.Int4
	ShuffledOptions []byte
}

const completeAttempt = `-- name: CompleteAttempt :one
UPDATE attempts
SET status = 'submitted',
    total_score = $2,
    completed_at = NOW()
WHERE id = $1 AND status = 'in_progress'
RETURNING id, user_id, exam_id, status, total_score, time_taken_seconds, started_at, completed_at, updated_at
`

type CompleteAttemptParams struct {
	ID         pgtype.UUID
	TotalScore pgtype.Float8
}

func (q *Queries) CompleteAttempt(ctx context.Context, arg CompleteAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, completeAttempt, arg.ID, arg.TotalScore)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExamID,
		&i.Status,
		&i.TotalScore,
		&i.TimeTakenSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAttemptsByExam = `-- name: CountAttemptsByExam :one
SELECT COUNT(*) AS total_attempts
FROM attempts
WHERE exam_id = $1
`

func (q *Queries) CountAttemptsByExam(ctx context.Context, examID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttemptsByExam, examID)
	var total_attempts int64
	err := row.Scan(&total_attempts)
	return total_attempts, err
}

const countQuestionSetsBySection = `-- name: CountQuestionSetsBySection :one
SELECT COUNT(*) AS total
FROM exam_question_sets
WHERE section_id = $1
`

func (q *Queries) CountQuestionSetsBySection(ctx context.Context, sectionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestionSetsBySection, sectionID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createAttempt = `-- name: CreateAttempt :one

INSERT INTO attempts (user_id, exam_id)
VALUES ($1,$2)
RETURNING id, user_id, exam_id, status, total_score, time_taken_seconds, started_at, completed_at, updated_at
`

type CreateAttemptParams struct {
	UserID pgtype.UUID
	ExamID pgtype.UUID
}

// ============================================================
// ATTEMPTS
// ============================================================
func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt, arg.UserID, arg.ExamID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExamID,
		&i.Status,
		&i.TotalScore,
		&i.TimeTakenSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExam = `-- name: CreateExam :one

INSERT INTO exams (name, exam_type, duration_minutes, total_marks)
VALUES ($1, $2, $3, $4)
RETURNING id, name, exam_type, duration_minutes, total_marks, is_active, created_at
`

type CreateExamParams struct {
	Name            string
	ExamType        interface{}
	DurationMinutes int32
	TotalMarks      int32
}

// ============================================================
// EXAMS
// ============================================================
func (q *Queries) CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error) {
	row := q.db.QueryRow(ctx, createExam,
		arg.Name,
		arg.ExamType,
		arg.DurationMinutes,
		arg.TotalMarks,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExamType,
		&i.DurationMinutes,
		&i.TotalMarks,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createQuestionSet = `-- name: CreateQuestionSet :one

INSERT INTO exam_question_sets (
  exam_id,
  section_id,
  question_set_id,
  question_count,
  difficulty_distribution
)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, exam_id, section_id, question_set_id, question_count, difficulty_distribution
`

type CreateQuestionSetParams struct {
	ExamID                 pgtype.UUID
	SectionID              pgtype.UUID
	QuestionSetID          string
	QuestionCount          int32
	DifficultyDistribution []byte
}

// ============================================================
// QUESTION SETS
// ============================================================
func (q *Queries) CreateQuestionSet(ctx context.Context, arg CreateQuestionSetParams) (ExamQuestionSet, error) {
	row := q.db.QueryRow(ctx, createQuestionSet,
		arg.ExamID,
		arg.SectionID,
		arg.QuestionSetID,
		arg.QuestionCount,
		arg.DifficultyDistribution,
	)
	var i ExamQuestionSet
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.SectionID,
		&i.QuestionSetID,
		&i.QuestionCount,
		&i.DifficultyDistribution,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one

INSERT INTO exam_sections (
  exam_id,
  name,
  subject_id,
  time_limit,
  question_count,
  order_index,
  is_switch_allowed
)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, exam_id, name, subject_id, time_limit, question_count, order_index, is_switch_allowed, is_active
`

type CreateSectionParams struct {
	ExamID          pgtype.UUID
	Name            string
	SubjectID       pgtype.UUID
	TimeLimit       pgtype.Int4
	QuestionCount   pgtype.Int4
	OrderIndex      pgtype.Int4
	IsSwitchAllowed pgtype.Bool
}

// ============================================================
// SECTIONS
// ============================================================
func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (ExamSection, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.ExamID,
		arg.Name,
		arg.SubjectID,
		arg.TimeLimit,
		arg.QuestionCount,
		arg.OrderIndex,
		arg.IsSwitchAllowed,
	)
	var i ExamSection
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.Name,
		&i.SubjectID,
		&i.TimeLimit,
		&i.QuestionCount,
		&i.OrderIndex,
		&i.IsSwitchAllowed,
		&i.IsActive,
	)
	return i, err
}

const createSubject = `-- name: CreateSubject :one

INSERT INTO subjects (name, description)
VALUES ($1, $2)
RETURNING id, name, description
`

type CreateSubjectParams struct {
	Name        string
	Description pgtype.Text
}

// ============================================================
// SUBJECTS
// ============================================================
func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.Name, arg.Description)
	var i Subject
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubject, id)
	return err
}

const disableExam = `-- name: DisableExam :exec
UPDATE exams
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DisableExam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableExam, id)
	return err
}

const evaluateAnswer = `-- name: EvaluateAnswer :exec
UPDATE answers
SET is_correct = $3,
    marks_awarded = $4
WHERE attempt_id = $1 AND question_id = $2
`

type EvaluateAnswerParams struct {
	AttemptID    pgtype.UUID
	QuestionID   string
	IsCorrect    pgtype.Bool
	MarksAwarded pgtype.Float8
}

func (q *Queries) EvaluateAnswer(ctx context.Context, arg EvaluateAnswerParams) error {
	_, err := q.db.Exec(ctx, evaluateAnswer,
		arg.AttemptID,
		arg.QuestionID,
		arg.IsCorrect,
		arg.MarksAwarded,
	)
	return err
}

const getActiveAttempt = `-- name: GetActiveAttempt :one
SELECT id, user_id, exam_id, status, total_score, time_taken_seconds, started_at, completed_at, updated_at
FROM attempts
WHERE user_id = $1
  AND exam_id = $2
  AND status = 'in_progress'
LIMIT 1
`

type GetActiveAttemptParams struct {
	UserID pgtype.UUID
	ExamID pgtype.UUID
}

func (q *Queries) GetActiveAttempt(ctx context.Context, arg GetActiveAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, getActiveAttempt, arg.UserID, arg.ExamID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExamID,
		&i.Status,
		&i.TotalScore,
		&i.TimeTakenSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnswerByAttemptAndQuestion = `-- name: GetAnswerByAttemptAndQuestion :one
SELECT id, attempt_id, question_id, selected_answer, is_correct, marks_awarded, question_snapshot
FROM answers
WHERE attempt_id = $1 AND question_id = $2
`

type GetAnswerByAttemptAndQuestionParams struct {
	AttemptID  pgtype.UUID
	QuestionID string
}

func (q *Queries) GetAnswerByAttemptAndQuestion(ctx context.Context, arg GetAnswerByAttemptAndQuestionParams) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswerByAttemptAndQuestion, arg.AttemptID, arg.QuestionID)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.SelectedAnswer,
		&i.IsCorrect,
		&i.MarksAwarded,
		&i.QuestionSnapshot,
	)
	return i, err
}

const getAnswersByAttempt = `-- name: GetAnswersByAttempt :many
SELECT id, attempt_id, question_id, selected_answer, is_correct, marks_awarded, question_snapshot
FROM answers
WHERE attempt_id = $1
`

func (q *Queries) GetAnswersByAttempt(ctx context.Context, attemptID pgtype.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, getAnswersByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.SelectedAnswer,
			&i.IsCorrect,
			&i.MarksAwarded,
			&i.QuestionSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, user_id, exam_id, status, total_score, time_taken_seconds, started_at, completed_at, updated_at FROM attempts WHERE id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, id pgtype.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExamID,
		&i.Status,
		&i.TotalScore,
		&i.TimeTakenSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttemptQuestions = `-- name: GetAttemptQuestions :many
SELECT attempt_id, question_id, section_id, order_index, shuffled_options
FROM attempt_question_map
WHERE attempt_id = $1
ORDER BY order_index
`

func (q *Queries) GetAttemptQuestions(ctx context.Context, attemptID pgtype.UUID) ([]AttemptQuestionMap, error) {
	rows, err := q.db.Query(ctx, getAttemptQuestions, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttemptQuestionMap
	for rows.Next() {
		var i AttemptQuestionMap
		if err := rows.Scan(
			&i.AttemptID,
			&i.QuestionID,
			&i.SectionID,
			&i.OrderIndex,
			&i.ShuffledOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttemptQuestionsBySection = `-- name: GetAttemptQuestionsBySection :many
SELECT attempt_id, question_id, section_id, order_index, shuffled_options
FROM attempt_question_map
WHERE attempt_id = $1
  AND section_id = $2
ORDER BY order_index
`

type GetAttemptQuestionsBySectionParams struct {
	AttemptID pgtype.UUID
	SectionID pgtype.UUID
}

func (q *Queries) GetAttemptQuestionsBySection(ctx context.Context, arg GetAttemptQuestionsBySectionParams) ([]AttemptQuestionMap, error) {
	rows, err := q.db.Query(ctx, getAttemptQuestionsBySection, arg.AttemptID, arg.SectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttemptQuestionMap
	for rows.Next() {
		var i AttemptQuestionMap
		if err := rows.Scan(
			&i.AttemptID,
			&i.QuestionID,
			&i.SectionID,
			&i.OrderIndex,
			&i.ShuffledOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttemptResult = `-- name: GetAttemptResult :one

SELECT id, total_score, time_taken_seconds, completed_at
FROM attempts
WHERE id = $1
`

type GetAttemptResultRow struct {
	ID               pgtype.UUID
	TotalScore       pgtype.Float8
	TimeTakenSeconds pgtype.Int4
	CompletedAt      pgtype.Timestamp
}

// ============================================================
// RESULTS & ANALYTICS
// ============================================================
func (q *Queries) GetAttemptResult(ctx context.Context, id pgtype.UUID) (GetAttemptResultRow, error) {
	row := q.db.QueryRow(ctx, getAttemptResult, id)
	var i GetAttemptResultRow
	err := row.Scan(
		&i.ID,
		&i.TotalScore,
		&i.TimeTakenSeconds,
		&i.CompletedAt,
	)
	return i, err
}

const getAttemptStatus = `-- name: GetAttemptStatus :one
SELECT status
FROM attempts
WHERE id = $1
`

func (q *Queries) GetAttemptStatus(ctx context.Context, id pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getAttemptStatus, id)
	var status interface{}
	err := row.Scan(&status)
	return status, err
}

const getAttemptsByExam = `-- name: GetAttemptsByExam :many
SELECT id, user_id, exam_id, status, total_score, time_taken_seconds, started_at, completed_at, updated_at
FROM attempts
WHERE exam_id = $1
`

func (q *Queries) GetAttemptsByExam(ctx context.Context, examID pgtype.UUID) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, getAttemptsByExam, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExamID,
			&i.Status,
			&i.TotalScore,
			&i.TimeTakenSeconds,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttemptsByExamPaginated = `-- name: GetAttemptsByExamPaginated :many
SELECT id, user_id, exam_id, status, total_score, time_taken_seconds, started_at, completed_at, updated_at
FROM attempts
WHERE exam_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type GetAttemptsByExamPaginatedParams struct {
	ExamID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetAttemptsByExamPaginated(ctx context.Context, arg GetAttemptsByExamPaginatedParams) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, getAttemptsByExamPaginated, arg.ExamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExamID,
			&i.Status,
			&i.TotalScore,
			&i.TimeTakenSeconds,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttemptsByUser = `-- name: GetAttemptsByUser :many
SELECT id, user_id, exam_id, status, total_score, time_taken_seconds, started_at, completed_at, updated_at
FROM attempts
WHERE user_id = $1
ORDER BY started_at DESC
`

func (q *Queries) GetAttemptsByUser(ctx context.Context, userID pgtype.UUID) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, getAttemptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExamID,
			&i.Status,
			&i.TotalScore,
			&i.TimeTakenSeconds,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAverageScoreByExam = `-- name: GetAverageScoreByExam :one
SELECT COALESCE(AVG(total_score), 0) AS avg_score
FROM attempts
WHERE exam_id = $1
  AND status = 'submitted'
`

func (q *Queries) GetAverageScoreByExam(ctx context.Context, examID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getAverageScoreByExam, examID)
	var avg_score interface{}
	err := row.Scan(&avg_score)
	return avg_score, err
}

const getExam = `-- name: GetExam :one
SELECT id, name, exam_type, duration_minutes, total_marks, is_active, created_at FROM exams WHERE id = $1
`

func (q *Queries) GetExam(ctx context.Context, id pgtype.UUID) (Exam, error) {
	row := q.db.QueryRow(ctx, getExam, id)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExamType,
		&i.DurationMinutes,
		&i.TotalMarks,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getExamSettings = `-- name: GetExamSettings :one
SELECT exam_id, is_published, shuffle_questions, shuffle_options, allow_section_switch FROM exam_settings WHERE exam_id = $1
`

func (q *Queries) GetExamSettings(ctx context.Context, examID pgtype.UUID) (ExamSetting, error) {
	row := q.db.QueryRow(ctx, getExamSettings, examID)
	var i ExamSetting
	err := row.Scan(
		&i.ExamID,
		&i.IsPublished,
		&i.ShuffleQuestions,
		&i.ShuffleOptions,
		&i.AllowSectionSwitch,
	)
	return i, err
}

const getExamWithSections = `-- name: GetExamWithSections :many
SELECT
  e.id AS exam_id,
  e.name AS exam_name,
  e.exam_type,
  e.duration_minutes,
  e.total_marks,

  s.id AS section_id,
  s.name AS section_name,
  s.order_index,
  s.question_count
FROM exams e
LEFT JOIN exam_sections s ON e.id = s.exam_id
WHERE e.id = $1
`

type GetExamWithSectionsRow struct {
	ExamID          pgtype.UUID
	ExamName        string
	ExamType        interface{}
	DurationMinutes int32
	TotalMarks      int32
	SectionID       pgtype.UUID
	SectionName     pgtype.Text
	OrderIndex      pgtype.Int4
	QuestionCount   pgtype.Int4
}

func (q *Queries) GetExamWithSections(ctx context.Context, id pgtype.UUID) ([]GetExamWithSectionsRow, error) {
	rows, err := q.db.Query(ctx, getExamWithSections, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExamWithSectionsRow
	for rows.Next() {
		var i GetExamWithSectionsRow
		if err := rows.Scan(
			&i.ExamID,
			&i.ExamName,
			&i.ExamType,
			&i.DurationMinutes,
			&i.TotalMarks,
			&i.SectionID,
			&i.SectionName,
			&i.OrderIndex,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAttempt = `-- name: GetLatestAttempt :one
SELECT id, user_id, exam_id, status, total_score, time_taken_seconds, started_at, completed_at, updated_at
FROM attempts
WHERE user_id = $1 AND exam_id = $2
ORDER BY started_at DESC
LIMIT 1
`

type GetLatestAttemptParams struct {
	UserID pgtype.UUID
	ExamID pgtype.UUID
}

func (q *Queries) GetLatestAttempt(ctx context.Context, arg GetLatestAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, getLatestAttempt, arg.UserID, arg.ExamID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExamID,
		&i.Status,
		&i.TotalScore,
		&i.TimeTakenSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionSetsByExam = `-- name: GetQuestionSetsByExam :many
SELECT id, exam_id, section_id, question_set_id, question_count, difficulty_distribution
FROM exam_question_sets
WHERE exam_id = $1
`

func (q *Queries) GetQuestionSetsByExam(ctx context.Context, examID pgtype.UUID) ([]ExamQuestionSet, error) {
	rows, err := q.db.Query(ctx, getQuestionSetsByExam, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExamQuestionSet
	for rows.Next() {
		var i ExamQuestionSet
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.SectionID,
			&i.QuestionSetID,
			&i.QuestionCount,
			&i.DifficultyDistribution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionScores = `-- name: GetSectionScores :many
SELECT attempt_id, section_id, score, correct, wrong
FROM attempt_section_scores
WHERE attempt_id = $1
`

func (q *Queries) GetSectionScores(ctx context.Context, attemptID pgtype.UUID) ([]AttemptSectionScore, error) {
	rows, err := q.db.Query(ctx, getSectionScores, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttemptSectionScore
	for rows.Next() {
		var i AttemptSectionScore
		if err := rows.Scan(
			&i.AttemptID,
			&i.SectionID,
			&i.Score,
			&i.Correct,
			&i.Wrong,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionsByExam = `-- name: GetSectionsByExam :many
SELECT id, exam_id, name, subject_id, time_limit, question_count, order_index, is_switch_allowed, is_active
FROM exam_sections
WHERE exam_id = $1 AND is_active = TRUE
ORDER BY order_index
`

func (q *Queries) GetSectionsByExam(ctx context.Context, examID pgtype.UUID) ([]ExamSection, error) {
	rows, err := q.db.Query(ctx, getSectionsByExam, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExamSection
	for rows.Next() {
		var i ExamSection
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.Name,
			&i.SubjectID,
			&i.TimeLimit,
			&i.QuestionCount,
			&i.OrderIndex,
			&i.IsSwitchAllowed,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubject = `-- name: GetSubject :one
SELECT id, name, description FROM subjects WHERE id = $1
`

func (q *Queries) GetSubject(ctx context.Context, id pgtype.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubject, id)
	var i Subject
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getSubjects = `-- name: GetSubjects :many
SELECT id, name, description FROM subjects
`

func (q *Queries) GetSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, getSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExams = `-- name: ListExams :many
SELECT id, name, exam_type, duration_minutes, total_marks, is_active, created_at
FROM exams
WHERE is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListExams(ctx context.Context) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listExams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExamType,
			&i.DurationMinutes,
			&i.TotalMarks,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamsPaginated = `-- name: ListExamsPaginated :many
SELECT id, name, exam_type, duration_minutes, total_marks, is_active, created_at
FROM exams
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListExamsPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListExamsPaginated(ctx context.Context, arg ListExamsPaginatedParams) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listExamsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExamType,
			&i.DurationMinutes,
			&i.TotalMarks,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamsWithStatus = `-- name: ListExamsWithStatus :many
SELECT e.id, e.name, e.exam_type, e.duration_minutes, e.total_marks, e.is_active, e.created_at, es.is_published
FROM exams e
LEFT JOIN exam_settings es ON e.id = es.exam_id
WHERE e.is_active = TRUE
ORDER BY e.created_at DESC
`

type ListExamsWithStatusRow struct {
	ID              pgtype.UUID
	Name            string
	ExamType        interface{}
	DurationMinutes int32
	TotalMarks      int32
	IsActive        pgtype.Bool
	CreatedAt       pgtype.Timestamp
	IsPublished     pgtype.Bool
}

func (q *Queries) ListExamsWithStatus(ctx context.Context) ([]ListExamsWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listExamsWithStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExamsWithStatusRow
	for rows.Next() {
		var i ListExamsWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExamType,
			&i.DurationMinutes,
			&i.TotalMarks,
			&i.IsActive,
			&i.CreatedAt,
			&i.IsPublished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedExams = `-- name: ListPublishedExams :many
SELECT e.id, e.name, e.exam_type, e.duration_minutes, e.total_marks, e.is_active, e.created_at
FROM exams e
JOIN exam_settings es ON e.id = es.exam_id
WHERE e.is_active = TRUE
  AND es.is_published = TRUE
ORDER BY e.created_at DESC
`

func (q *Queries) ListPublishedExams(ctx context.Context) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listPublishedExams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExamType,
			&i.DurationMinutes,
			&i.TotalMarks,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishExam = `-- name: PublishExam :exec
INSERT INTO exam_settings (exam_id, is_published)
VALUES ($1, TRUE)
ON CONFLICT (exam_id)
DO UPDATE SET is_published = TRUE
`

func (q *Queries) PublishExam(ctx context.Context, examID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, publishExam, examID)
	return err
}

const updateExam = `-- name: UpdateExam :exec
UPDATE exams
SET name = $2,
    duration_minutes = $3,
    total_marks = $4
WHERE id = $1
`

type UpdateExamParams struct {
	ID              pgtype.UUID
	Name            string
	DurationMinutes int32
	TotalMarks      int32
}

func (q *Queries) UpdateExam(ctx context.Context, arg UpdateExamParams) error {
	_, err := q.db.Exec(ctx, updateExam,
		arg.ID,
		arg.Name,
		arg.DurationMinutes,
		arg.TotalMarks,
	)
	return err
}

const updateQuestionSet = `-- name: UpdateQuestionSet :exec
UPDATE exam_question_sets
SET question_count = $2,
    difficulty_distribution = $3
WHERE id = $1
`

type UpdateQuestionSetParams struct {
	ID                     pgtype.UUID
	QuestionCount          int32
	DifficultyDistribution []byte
}

func (q *Queries) UpdateQuestionSet(ctx context.Context, arg UpdateQuestionSetParams) error {
	_, err := q.db.Exec(ctx, updateQuestionSet, arg.ID, arg.QuestionCount, arg.DifficultyDistribution)
	return err
}

const updateSection = `-- name: UpdateSection :exec
UPDATE exam_sections
SET name = $2,
    time_limit = $3,
    question_count = $4,
    order_index = $5
WHERE id = $1
`

type UpdateSectionParams struct {
	ID            pgtype.UUID
	Name          string
	TimeLimit     pgtype.Int4
	QuestionCount pgtype.Int4
	OrderIndex    pgtype.Int4
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) error {
	_, err := q.db.Exec(ctx, updateSection,
		arg.ID,
		arg.Name,
		arg.TimeLimit,
		arg.QuestionCount,
		arg.OrderIndex,
	)
	return err
}

const upsertAnswer = `-- name: UpsertAnswer :exec

INSERT INTO answers (
  attempt_id,
  question_id,
  selected_answer,
  question_snapshot
)
VALUES ($1,$2,$3,$4)
ON CONFLICT (attempt_id,question_id)
DO UPDATE SET
  selected_answer = EXCLUDED.selected_answer,
  question_snapshot = EXCLUDED.question_snapshot
`

type UpsertAnswerParams struct {
	AttemptID        pgtype.UUID
	QuestionID       string
	SelectedAnswer   []byte
	QuestionSnapshot []byte
}

// ============================================================
// ANSWERS
// ============================================================
func (q *Queries) UpsertAnswer(ctx context.Context, arg UpsertAnswerParams) error {
	_, err := q.db.Exec(ctx, upsertAnswer,
		arg.AttemptID,
		arg.QuestionID,
		arg.SelectedAnswer,
		arg.QuestionSnapshot,
	)
	return err
}

const upsertExamSettings = `-- name: UpsertExamSettings :one

INSERT INTO exam_settings (
  exam_id,
  is_published,
  shuffle_questions,
  shuffle_options,
  allow_section_switch
)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (exam_id)
DO UPDATE SET
  is_published = EXCLUDED.is_published,
  shuffle_questions = EXCLUDED.shuffle_questions,
  shuffle_options = EXCLUDED.shuffle_options,
  allow_section_switch = EXCLUDED.allow_section_switch
RETURNING exam_id, is_published, shuffle_questions, shuffle_options, allow_section_switch
`

type UpsertExamSettingsParams struct {
	ExamID             pgtype.UUID
	IsPublished        pgtype.Bool
	ShuffleQuestions   pgtype.Bool
	ShuffleOptions     pgtype.Bool
	AllowSectionSwitch pgtype.Bool
}

// ============================================================
// EXAM SETTINGS
// ============================================================
func (q *Queries) UpsertExamSettings(ctx context.Context, arg UpsertExamSettingsParams) (ExamSetting, error) {
	row := q.db.QueryRow(ctx, upsertExamSettings,
		arg.ExamID,
		arg.IsPublished,
		arg.ShuffleQuestions,
		arg.ShuffleOptions,
		arg.AllowSectionSwitch,
	)
	var i ExamSetting
	err := row.Scan(
		&i.ExamID,
		&i.IsPublished,
		&i.ShuffleQuestions,
		&i.ShuffleOptions,
		&i.AllowSectionSwitch,
	)
	return i, err
}

const upsertSectionScore = `-- name: UpsertSectionScore :exec

INSERT INTO attempt_section_scores (
  attempt_id,
  section_id,
  score,
  correct,
  wrong
)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (attempt_id,section_id)
DO UPDATE SET
  score = EXCLUDED.score,
  correct = EXCLUDED.correct,
  wrong = EXCLUDED.wrong
`

type UpsertSectionScoreParams struct {
	AttemptID pgtype.UUID
	SectionID pgtype.UUID
	Score     pgtype.Float8
	Correct   pgtype.Int4
	Wrong     pgtype.Int4
}

// ============================================================
// SECTION SCORES
// ============================================================
func (q *Queries) UpsertSectionScore(ctx context.Context, arg UpsertSectionScoreParams) error {
	_, err := q.db.Exec(ctx, upsertSectionScore,
		arg.AttemptID,
		arg.SectionID,
		arg.Score,
		arg.Correct,
		arg.Wrong,
	)
	return err
}
